/* ALTA SYSTEM: multi-country selection, independent region browsing, local PDF export. */
'use strict';
const $=s=>document.querySelector(s);
const params=new URLSearchParams(location.search),demoMode=params.get('demo')==='1',dataRoot=demoMode?'demo/':'data/';
const regions={Asia:'アジア',Americas:'南北アメリカ',Europe:'ヨーロッパ',Oceania:'オセアニア',Africa:'アフリカ',Antarctic:'南極'};
let region=params.get('region')||'all',index=null,catalog=[],feeds=new Map(),visible=[],layers=new Map(),loading=false,failures=[];
let selectedCountries=new Set((params.get('countries')??params.get('country')??(demoMode?'JP,KR,US,GB,AU':'JP')).toUpperCase().split(',').filter(c=>/^[A-Z]{2}$/.test(c)));
const selectedAlerts=new Set();
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};
const time=v=>v?new Date(v).toLocaleString('ja-JP',{timeZone:'UTC'})+' UTC':'未取得';
const accuracy={'provider-boundary':'提供元の境界','provider-circle':'提供元の円','qline-envelope':'Q行の概略円（正確な境界ではありません）'};
const expired=p=>p.validTo&&p.validTo!=='PERM'&&Date.parse(p.validTo)<=Date.now();
const countryName=c=>catalog.find(x=>x.code===c)?.name||c;
const map=typeof L!=='undefined'?L.map('map',{worldCopyJump:false,zoomControl:false}).setView([28,125],3):null;
let group=null;
if(map){L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);group=L.featureGroup().addTo(map);}
$('#mode-link').href=demoMode?'./':'?demo=1';$('#mode-link').textContent=demoMode?'実データへ':'デモを見る';
function syncURL(){const p=new URLSearchParams(location.search);p.delete('country');p.set('countries',[...selectedCountries].sort().join(','));region==='all'?p.delete('region'):p.set('region',region);history.replaceState(null,'',location.pathname+'?'+p.toString());}
function allFeatures(){const m=new Map();for(const data of feeds.values())for(const f of data.features||[])if(!expired(f.properties))m.set(f.id,f);return m;}
function reportSelection(){const all=allFeatures();return [...selectedAlerts].map(id=>all.get(id)).filter(Boolean);}
function pruneSelection(){const all=allFeatures();for(const id of selectedAlerts)if(!all.has(id))selectedAlerts.delete(id);}
function updateReportUI(){const selected=reportSelection();$('#pdf-button').disabled=!selected.length;$('#pdf-count').textContent=`選択 ${selected.length}件（表示条件に隠れた選択も含む）`;document.querySelectorAll('[data-alert-id]').forEach(n=>n.checked=selectedAlerts.has(n.dataset.alertId));for(const [id,l] of layers)l.setStyle({color:selectedAlerts.has(id)?'#f59e0b':'#ef4444',weight:selectedAlerts.has(id)?4:2});}
function toggleAlert(id,checked){checked?selectedAlerts.add(id):selectedAlerts.delete(id);updateReportUI();}
function alertCheck(f){const label=node('label',null,'report-check');const c=node('input');c.type='checkbox';c.dataset.alertId=f.id;c.checked=selectedAlerts.has(f.id);c.setAttribute('aria-label',f.properties.name+'をPDFに選択');c.onchange=()=>toggleAlert(f.id,c.checked);label.append(c,node('span','PDFに選択'));return label;}
function details(f){const p=f.properties,el=node('article',null,'popup');el.append(node('small',p.type+' / '+countryName(p.country)),node('h3',p.name),alertCheck(f));const dl=node('dl');for(const [k,v] of [['識別子',p.id],['Qコード',p.qcode||'未提供'],['区域情報',accuracy[p.accuracy]],['高度',`${p.lower??'未提供'} — ${p.upper??'未提供'}`],['開始',p.validFrom||'未提供'],['終了',p.validTo||'未提供'],['時間条件',p.schedule||p.timeStatus],['出典',p.source]])dl.append(node('dt',k),node('dd',v));el.append(dl,node('p',p.text||''));return el;}
function positions(g){if(g.type==='Point')return [g.coordinates];return g.type==='Polygon'?g.coordinates.flat():g.coordinates.flat(2);}
// The largest empty longitude gap places JP + US around the Pacific, avoiding an unnecessary world-wide view.
function longitudeAnchor(fs){const xs=fs.flatMap(f=>positions(f.geometry).map(p=>(p[0]+360)%360)).sort((a,b)=>a-b);if(!xs.length)return 0;let gap=-1,start=xs[0];for(let i=0;i<xs.length;i++){const next=i+1<xs.length?xs[i+1]:xs[0]+360;if(next-xs[i]>gap){gap=next-xs[i];start=next%360;}}return start;}
function shiftedGeometry(g,anchor){const pts=positions(g),center=pts.reduce((s,p)=>s+p[0],0)/pts.length;let target=(center+360)%360;if(target<anchor)target+=360;const offset=360*Math.round((target-center)/360);const shift=p=>[p[0]+offset,p[1]];return {type:g.type,coordinates:g.type==='Point'?shift(g.coordinates):g.type==='Polygon'?g.coordinates.map(r=>r.map(shift)):g.coordinates.map(poly=>poly.map(r=>r.map(shift)))};}
function draw(f,anchor){const p=f.properties,g=shiftedGeometry(f.geometry,anchor),selected=selectedAlerts.has(f.id);const style={color:selected?'#f59e0b':'#ef4444',weight:selected?4:2,fillColor:'#ef4444',fillOpacity:.14,dashArray:p.accuracy==='qline-envelope'?'6 5':undefined};let l;if(g.type==='Point'){if(!Number.isFinite(p.radius_m)||p.radius_m<=0)return;const [lon,lat]=g.coordinates;l=L.circle([lat,lon],{...style,radius:p.radius_m});}else l=L.geoJSON({...f,geometry:g},{style});l.bindPopup(()=>details(f),{maxWidth:340});l.on('click',()=>toggleAlert(f.id,!selectedAlerts.has(f.id)));group.addLayer(l);layers.set(f.id,l);return l;}
function fitVisible(){if(!map)return;if(group.getLayers().length){map.fitBounds(group.getBounds(),{padding:[50,50],maxZoom:8,animate:false});}else{const chosen=catalog.filter(c=>selectedCountries.has(c.code));if(chosen.length===1)map.setView(chosen[0].center,4,{animate:false});else if(chosen.length){const a=longitudeAnchor(chosen.map(c=>({geometry:{type:'Point',coordinates:[c.center[1],c.center[0]]}})));map.fitBounds(chosen.map(c=>{let lon=(c.center[1]+360)%360;if(lon<a)lon+=360;return [c.center[0],lon]}),{padding:[50,50],maxZoom:5,animate:false});}else map.setView([25,20],2);}}
function jumpCountry(code){if(!map)return;const ls=visible.filter(f=>f.properties.country===code).map(f=>layers.get(f.id)).filter(Boolean);if(ls.length)map.fitBounds(L.featureGroup(ls).getBounds(),{padding:[45,45],maxZoom:8,animate:false});else{const c=catalog.find(c=>c.code===code);if(c)map.setView(c.center,4,{animate:false});}}
function countryStatus(code){const c=index?.countries.find(c=>c.code===code);if(!c)return demoMode?'デモなし':'データ未設定';const m=feeds.get(code)?.metadata;if(failures.includes(code))return '再読込失敗';if(m?.status==='unconfigured')return 'API未接続';return demoMode?'架空デモ':m?.status==='error'?'取得失敗':m?.lastSuccess?'取得済み':'未取得';}
function updateChoices(){const query=$('#country-search').value.trim().toLowerCase();const list=catalog.filter(c=>(region==='all'||c.region===region)&&(!query||`${c.name} ${c.english} ${c.code}`.toLowerCase().includes(query)));const groups=[];for(const [r,title]of Object.entries(regions)){const members=list.filter(c=>c.region===r);if(!members.length)continue;const section=node('section',null,'country-region');section.append(node('h3',title));for(const c of members){const row=node('div',null,'country-row'),check=node('input'),jump=node('button',c.name+' / '+c.code);check.type='checkbox';check.checked=selectedCountries.has(c.code);check.setAttribute('aria-label',c.name+'を表示');check.onchange=()=>{check.checked?selectedCountries.add(c.code):selectedCountries.delete(c.code);syncURL();render(true);updateChoices();};jump.type='button';jump.title='地図を'+c.name+'へ移動';jump.setAttribute('aria-label',c.name+'へ移動');jump.onclick=()=>jumpCountry(c.code);row.append(check,jump,node('small',countryStatus(c.code)));section.append(row);}groups.push(section);}$('#country-list').replaceChildren(...groups);$('#country-count').textContent=`選択 ${selectedCountries.size} / ${catalog.length} 国・地域`;document.querySelectorAll('#tabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.region===region)));}
function render(fit=false){group?.clearLayers();layers.clear();visible=[];const rows=[],missing=[];const kinds=new Set([...document.querySelectorAll('[data-kind]:checked')].map(x=>x.dataset.kind));const query=$('#search').value.trim().toLowerCase();const chosen=catalog.filter(c=>selectedCountries.has(c.code));const matches=p=>!expired(p)&&kinds.has(p.type)&&(!query||`${p.id} ${p.name} ${p.text} ${p.qcode}`.toLowerCase().includes(query));for(const c of chosen){const data=feeds.get(c.code);if(!data)continue;for(const f of data.features){const p=f.properties;if(!matches(p)||(!$('#approx').checked&&p.accuracy==='qline-envelope'))continue;visible.push(f);}for(const p of data.unplotted||[])if(matches(p))missing.push(node('p',`${c.code} / ${p.name} — ${p.unplottedReason}`));}const anchor=longitudeAnchor(visible);for(const f of visible){const p=f.properties,l=map?draw(f,anchor):null,row=node('div',null,'area');const b=node('button',null,'area-detail');b.append(node('span',p.country+' / '+p.type,'area-type'),node('strong',p.name),node('small',p.id+(p.timeStatus==='future'?' · 開始前':'')+(p.accuracy==='qline-envelope'?' · 概略':'')));b.onclick=()=>{if(l){map.fitBounds(l.getBounds(),{padding:[45,45],maxZoom:8,animate:false});l.openPopup();}};row.append(b,alertCheck(f));rows.push(row);}$('#count').textContent=String(visible.length).padStart(2,'0');$('#areas').replaceChildren(...(rows.length?rows:[node('p','表示対象はありません。未接続の国は警報を取得していません。','empty')]));$('#unplotted-count').textContent=`未描画の警報 ${missing.length}件`;$('#unplotted-list').replaceChildren(...missing);$('#map-title').textContent=chosen.length===1?chosen[0].name+'の航空警報':`${chosen.length} 国・地域の航空警報`;
const pending=chosen.filter(c=>!feeds.has(c.code)||feeds.get(c.code).metadata.status==='unconfigured');const stale=chosen.filter(c=>{const m=feeds.get(c.code)?.metadata;return m&&m.status!=='unconfigured'&&(failures.includes(c.code)||m.status==='error'||(!m.demo&&(!m.lastSuccess||Date.now()-Date.parse(m.lastSuccess)>3600000)));});const note=[];if(demoMode)note.push('DEMO：すべて架空');if(pending.length)note.push(`${pending.length} 国・地域は${demoMode?'デモなし':'API未接続・データ未設定'}`);if(stale.length)note.push('更新失敗・古いデータ：'+stale.map(c=>c.code).join(', '));if(!selectedCountries.size)note.push('対象国をチェックしてください');if(!map)note.push('地図ライブラリの読込失敗');$('#notice').textContent=note.join(' / ')||'取得済みスナップショット · 詳細の時刻と条件を確認';$('#notice').classList.toggle('warning',pending.length>0||stale.length>0);$('#mode').textContent=demoMode?'DEMO DATA':pending.length?'NOTAM 未接続を含む':'NOTAM SNAPSHOT';$('#updated').textContent=demoMode?'架空データ・実API未接続':chosen.filter(c=>feeds.get(c.code)?.metadata.lastSuccess).map(c=>c.code+': '+time(feeds.get(c.code).metadata.lastSuccess)).join(' / ')||'実NOTAM未取得';pruneSelection();updateReportUI();if(fit)fitVisible();}
async function json(url){const r=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
async function refresh(first=false){if(loading)return;loading=true;$('#refresh').disabled=true;try{const [next,countries]=await Promise.all([json(dataRoot+'index.json'),catalog.length?Promise.resolve(null):json('countries.json')]);if(next.schemaVersion!==1||!Array.isArray(next.countries))throw Error('schema');if(countries)catalog=countries.countries.sort((a,b)=>a.name.localeCompare(b.name,'ja'));selectedCountries=new Set([...selectedCountries].filter(c=>catalog.some(x=>x.code===c)));index=next;failures=[];const current=new Set(index.countries.map(c=>c.code));for(const c of feeds.keys())if(!current.has(c))feeds.delete(c);for(let i=0;i<index.countries.length;i+=8){await Promise.all(index.countries.slice(i,i+8).map(async c=>{try{if(!/^[A-Z]{2}$/.test(c.code)||c.file!==c.code+'.json')throw Error('path');const data=c.status==='unconfigured'?{features:[],unplotted:[],metadata:c}:await json(dataRoot+c.file);if(!Array.isArray(data.features)||data.metadata.country!==c.code||data.metadata.demo!==index.demo)throw Error('snapshot');feeds.set(c.code,data);}catch{failures.push(c.code);}}));}updateChoices();syncURL();render(first);}catch{$('#notice').textContent='一覧の取得失敗。前回の表示を保持しています。';}finally{loading=false;$('#refresh').disabled=false;}}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-region]');if(!b)return;region=b.dataset.region;updateChoices();syncURL();};$('#country-search').oninput=updateChoices;
$('#countries-clear').onclick=()=>{selectedCountries.clear();syncURL();updateChoices();render(true);};$('#countries-all').onclick=()=>{const q=$('#country-search').value.trim().toLowerCase();for(const c of catalog)if((region==='all'||c.region===region)&&(!q||`${c.name} ${c.english} ${c.code}`.toLowerCase().includes(q)))selectedCountries.add(c.code);syncURL();updateChoices();render(true);};
$('#search').oninput=()=>render();document.querySelectorAll('[data-kind],#approx').forEach(el=>el.onchange=()=>render());$('#refresh').onclick=()=>refresh();$('#fit').onclick=fitVisible;$('#pdf-clear').onclick=()=>{selectedAlerts.clear();updateReportUI();};
$('#pdf-button').onclick=async()=>{const button=$('#pdf-button');button.disabled=true;$('#pdf-status').textContent='PDFを作成中…';try{const records=structuredClone(reportSelection());if(!records.length)throw Error('警報を選択してください。');await AltaReport.download(records,{demo:demoMode,countryName,feeds});$('#pdf-status').textContent=`${records.length}件のPDFをダウンロードしました。印刷はPDFを開いて行えます。`;}catch(e){$('#pdf-status').textContent='PDF作成失敗：'+e.message;}finally{updateReportUI();}};
if(region!=='all'&&!regions[region])region='all';refresh(true);setInterval(()=>refresh(),30*60*1000);setInterval(()=>{if(index&&!loading)render();},60*1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
